#!/bin/bash
#Progammer : Kurniawan. trainingxcode@gmail.com. xcode.or.id.
#Program ini dapat digunakan untuk personal ataupun komersial.
#X-code Media - xcode.or.id / xcodetraining.com 
again='y'
while [ $again == 'Y' ] || [ $again == 'y' ];
do
clear
echo "====================================================================";
echo " X-code Pandawa Router for Ubuntu 16.04 Server                      ";
echo " Progammer : Kurniawan. xcode.or.id                                 ";
echo " Version 1.0.1 - 11/05/2018                                         ";
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-";
echo " Router & Server pendukung router                                   ";
echo " [1]  Install X-code Pandawa (Untuk ganti nama ke eth0 dan eth1)    ";
echo " [2]  Setting IP Address untuk eth0 dan eth1                        ";
echo " [3]  Install NAT, DHCP Server & Bandwidth monitoring               ";
echo " [4]  Install HTB untuk bandwidth managemen                         ";
echo " [5]  Install Squid untuk log dan cache pada client                 ";
echo " [6]  Setting DHCP Server                                           ";
echo " [7]  Setting HTB Bandwidth managemen                               ";
echo " [8]  Matikan HTB Bandwidth managemen                               ";
echo " [9]  Hidupkan HTB Bandwidth managemen                              ";
echo " [10] Jalankan monitoring Bandwidth                                 ";
echo " [11] Port Forwarding                                               ";
echo " [12] Pasang Squid + Log (transparent)                              ";
echo " [13] Pasang Squid + Log + Cache (transparent)                      ";
echo " [14] Install VPN Server PPTP                                       ";
echo " [15] Setting ip client VPN Server                                  ";
echo " [16] Setting Password VPN Server                                   ";
echo " [17] Setting ms-dns pada VPN Server                                ";
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=";
echo " Log dan lainnya                                                    ";
echo " [18] Lihat Log apa yang dibuka client (real time)                  ";
echo " [19] Lihat log semua log yang tersimpan                            ";
echo " [20] Lihat ukuran cache squid                                      ";
echo " [21] Edit squid.conf                                               ";
echo " [22] Tambahkan NAT,  HTB dll pada rc.local (Autorun)               ";
echo " [23] Edit rc.local                                                 ";
echo " [24] Reboot                                                        ";
echo " [25] Exit                                                          ";
echo "====================================================================";
read -p " Masukkan Nomor Pilihan Anda [1 - 25] : " choice;
echo "";
case $choice in
1)  if [ -z "$(sudo ls -A /etc/default/grub)" ]; then
    echo "Tidak terdeteksi grub, anda yakin pakai Ubuntu 16.04 ?"
    else
    cp support/grub /etc/default/grub
    grub-mkconfig -o /boot/grub/grub.cfg
    cp support/resolved.conf /etc/systemd/
    sudo systemctl restart systemd-resolved
	read -p "Tekan enter untuk restart"
    reboot
	fi
    ;;
2)  if [ -z "$(ls -l /etc/network/interfaces)" ]; then
    echo "Tidak terdeteksi ada /etc/network/interfaces"
    else
    cp support/interfaces /etc/network/
    sudo nano /etc/network/interfaces
    read -p "Apakah anda mau restart koneksi eth0 & eth1 sekarang? y/n :" -n 1 -r
    echo 
        if [[ ! $REPLY =~ ^[Nn]$ ]]
        then
        ip addr flush eth0 && sudo systemctl restart networking.service
        ip addr flush eth1 && sudo systemctl restart networking.service
        sudo ifconfig
        fi
    fi
    ;;
3)  read -p "Apakah anda mau yakin mau install NAT, DHCP Server, dan iptraf ? y/n :" -n 1 -r
    echo  ""
    if [[ ! $REPLY =~ ^[Nn]$ ]]
    then
    sudo sysctl -w net.ipv4.ip_forward=1
    sudo /sbin/iptables -P FORWARD ACCEPT
    sudo /sbin/iptables --table nat -A POSTROUTING -o eth0 -j MASQUERADE
    echo "NAT sudah diinstall"
    sudo apt-get install isc-dhcp-server
    sudo mv /etc/dhcp/dhcp.conf /tmp
    sudo cp support/dhcpd.conf /etc/dhcp
    sudo nano /etc/dhcp/dhcpd.conf
    sudo service isc-dhcp-server restart
    echo "DHCP Server sudah diinstall"
    sudo apt-get install iptraf
    echo "iptraff sudah diinstall"
    fi
    ;;

4)  read -p "Apakah anda yakin install HTB untuk bandwidth managemen  ? y/n :" -n 1 -r
    echo  ""
    if [[ ! $REPLY =~ ^[Nn]$ ]]
    then
    if [ -z "$(ls -l /etc/init.d/rc.htb)" ]; then
    sudo cp support/HTB-tools-0.3.0a-i486-1.tgz /usr/local/src
    sudo tar -zxvf /usr/local/src/HTB-tools-0.3.0a-i486-1.tgz -C /usr/local/src/ 
    sudo mv /usr/local/src/sbin/htb /sbin
    sudo mv /usr/local/src/sbin/q_parser /sbin
    sudo mv /usr/local/src/sbin/q_show /sbin
    sudo mv /usr/local/src/sbin/htbgen /sbin
    sudo mv /usr/local/src/sbin/q_checkcfg /sbin
    sudo mv /usr/local/src/etc/htb/ /etc
    sudo mv /etc/htb/eth0-qos.cfg.new /etc/htb/eth0-qos.cfg
    sudo mv /etc/htb/eth1-qos.cfg.new /etc/htb/eth1-qos.cfg
    sudo mv /usr/local/src/etc/rc.d/rc.htb.new /etc/init.d/rc.htb
    sudo chmod 755 /etc/init.d/rc.htb
    sudo nano /etc/htb/eth1-qos.cfg
    sudo /etc/init.d/rc.htb start_eth1
    echo "hbt sudah diinstall"
    else
    echo "hbt sudah ada, tidak perlu diinstall lagi"
    fi
    fi
    ;;

5)  read -p "Apakah anda yakin install Squid  ? y/n :" -n 1 -r
    echo  ""
    if [[ ! $REPLY =~ ^[Nn]$ ]]
    then
    sudo apt-get install squid3
    fi
    ;;

6)  if [ -z "$(ls -A /etc/dhcp/dhcpd.conf)" ]; then
    echo "Tidak terdeteksi DHCP Server"
    else
    echo "Setting DHCP Server"
    sudo nano /etc/dhcp/dhcpd.conf
    service isc-dhcp-server restart
    fi
    ;;   

7)  if [ -z "$(ls -A /etc/init.d/rc.htb)" ]; then
    echo "Tidak terdeteksi Htb - Bandiwidth managemen"
    else
    echo "Setting htb"
    sudo nano /etc/htb/eth1-qos.cfg
    sudo /etc/init.d/rc.htb stop_eth1
    sudo /etc/init.d/rc.htb start_eth1
    fi
    ;;

8)  if [ -z "$(ls -A /etc/init.d/rc.htb)" ]; then
    echo "Tidak terdeteksi Htb - Bandiwidth managemen"
    else
    sudo /etc/init.d/rc.htb stop_eth1
    echo "htb sudah dimatikan"
    fi
    ;;

9)  if [ -z "$(ls -A /etc/init.d/rc.htb)" ]; then
    echo "Tidak terdeteksi Htb - Bandiwidth managemen"
    else
    sudo /etc/init.d/rc.htb start_eth1
    echo "htb bandwidth managemen sudah dihidupkan"
    fi
    ;;

10) sudo iptraf
    ;;


11) echo -n "Masukkan ip WAN: "
    read ipwan
    echo -n "Masukkan ip LAN: "
    read iplan
    echo -n "Masukkan port: "
    read portip
    sudo sysctl -w net.ipv4.ip_forward=1
    sudo iptables -t nat -A PREROUTING -j DNAT -d $ipwan -p tcp --dport $portip --to $iplan
    echo "Port forwading telah dilakukan"
    echo "Jika ingin tetap jalan setelah restart pastikan edit pada rc.local lalu aktifkan untuk port forwarding dengan menghilangkan tanda # lalu ganti ip address WAN, Port yang mau diarahkan dan IP address komputer LAN yang akan dituju."
    echo "Sebelum edit rc.local, tambahkan dulu NAT, HTB, dll ke rc.local yang ada pada menu"
    ;;

12) echo -n "Masukkan ip  LAN: "
    read iplan2
    if [ -z "$(ls -A /etc/squid/squid.conf)" ]; then
    echo "Squid tidak terdeteksi"
    else
    rm /etc/squid/squid.conf
    sudo cp support/squid1/squid.conf /etc/squid/
    sudo iptables -t nat -A PREROUTING -i eth1 -p tcp -m tcp --dport 80 -j DNAT --to-destination $iplan2:3127
    echo "Jika ingin tetap jalan setelah restart pastikan edit pada rc.local lalu aktifkan iptables untuk mengarahkan port 80 ke port squid 3127 dengan menghilangkan tanda #. Jangan lupa diganti ip address LAN-nya."
    echo "Sebelum edit rc.local, tambahkan dulu NAT, HTB, dll ke rc.local yang ada pada menu"
    read -p "Log akan aktif jika linux sudah dilakukan restart"
    fi
    ;;

13) echo -n "Masukkan ip  LAN: "
    read iplan3
    if [ -z "$(ls -l /etc/squid/squid.conf)" ]; then
    echo "Squid tidak terdeteksi"
    else
    rm /etc/squid/squid.conf
    sudo cp support/squid2/squid.conf /etc/squid/
    sudo iptables -t nat -A PREROUTING -i eth1 -p tcp -m tcp --dport 80 -j DNAT --to-destination $iplan3:3127
    echo "Jika ingin tetap jalan setelah restart pastikan edit pada rc.local lalu aktifkan iptables untuk mengarahkan port 80 ke port squid 3127 dengan menghilangkan tanda #. Jangan lupa diganti ip address lan-nya."
    echo "Sebelum edit rc.local, tambahkan dulu NAT, HTB, dll ke rc.local yang ada pada menu"
    read -p "Log akan aktif jika linux sudah dilakukan restart"
    fi
    ;;

14) read -p "Apakah anda yakin install VPN Server PPTP  ? y/n :" -n 1 -r
    echo  ""
    if [[ ! $REPLY =~ ^[Nn]$ ]]
    then
    if [ -z "$(ls -l /etc/pptpd.conf)" ]; then
    echo "Install PPTP Server" 
    sudo apt-get install pptpd
    sudo cp support/etc/pptpd.conf /etc
    sudo cp support/chap-secrets /etc/ppp
    sudo cp support/ppptpd-options /etc/ppp
    sudo nano /etc/pptpd.conf
    sudo nano /etc/ppp/chap-secrets
    sudo nano /etc/ppp/pptpd-options
    service pptpd restart
    else
    echo "Sudah ada PPTP Server"
    fi
    fi
    ;;

15) if [ -z "$(ls -l /etc/pptpd.conf)" ]; then
    echo "Tidak terdeteksi file pptpd.conf pada VPN Server"
    else
    echo "Edit pptpd.conf" 
    sudo nano /etc/pptpd.conf
    service pptpd restart
    fi
    ;;

16) if [ -z "$(ls -l /etc/ppp/chap-secrets)" ]; then
    echo "Tidak terdeteksi file chap-secrets pada VPN Server"
    else
    echo "Edit file chap-secrets" 
    sudo nano /etc/ppp/chap-secrets
    service pptpd restart
    fi
    ;;

17) if [ -z "$(ls -l /etc/pptpd.conf)" ]; then
    echo "Tidak terdeteksi file pptpd-options pada VPN Server"
    else
    echo "Edit file pptpd-options" 
    sudo nano /etc/ppp/pptpd-options
    service pptpd restart
    fi
    ;;

18) if [ -z "$(ls -l /var/log/squid/access.log)" ]; then
    echo "Tidak terdeteksi log access pada squid"
    else
    sudo tail -f /var/log/squid/access.log
    fi 
    ;;
 
19) if [ -z "$(ls -l /var/log/squid/access.log)" ]; then
    echo "Tidak terdeteksi log access pada squid"
    else
    sudo nano /var/log/squid/access.log
    fi
    ;;

20) du -s /var/spool/squid
    read -p "Tekan enter untuk melanjutkan"
    ;;

21) if [ -z "$(ls -l /etc/squid/squid.conf)" ]; then
    echo "Tidak terdeteksi squid"
    else
    sudo nano /etc/squid/squid.conf
    fi
    ;;

22) if [ -z "$(sudo ls -A /etc/rc.local)" ]; then
    echo "Tidak terdeteksi ada file rc.local di /etc/"
    else
    echo "File rc.local di folder /etc/ disisipkan NAT dan HBT"
    sudo sed -i -e '$i \sudo sysctl -w net.ipv4.ip_forward=1\n' /etc/rc.local
    sudo sed -i -e '$i \/sbin/iptables -P FORWARD ACCEPT\n' /etc/rc.local
    sudo sed -i -e '$i \/sbin/iptables --table nat -A POSTROUTING -o eth0 -j MASQUERADE\n' /etc/rc.local
    sudo sed -i -e '$i \/etc/init.d/rc.htb start_eth1\n' /etc/rc.local
    sudo sed -i -e '$i \#sysctl -w net.ipv4.ip_forward=1\n' /etc/rc.local
    sudo sed -i -e '$i \#iptables -t nat -A PREROUTING -j DNAT -d ipaddresswan -p tcp --dport portyangdiforward --to ipaddresslan\n' /etc/rc.local
    sudo sed -i -e '$i \#iptables -t nat -A PREROUTING -i eth1 -p tcp -m tcp --dport 80 -j DNAT --to-destination ipaddresslan:3127\n' /etc/rc.local
    fi
    ;; 

23) sudo nano /etc/rc.local
    ;;

24) read -p "Apakah anda yakin akan restart? y/n :" -n 1 -r
    echo 
    if [[ ! $REPLY =~ ^[Nn]$ ]]
    then
    reboot
    fi
    ;;

25) exit
    ;;
*)    echo "Maaf, menu tidak ada"
esac
echo ""
echo "X-code Pandawa"
echo "Oleh Kurniawan - trainingxcode@gmail.com. xcode.or.id"
echo ""
echo -n "Kembali ke menu? [y/n]: ";
read again;
while [ $again != 'Y' ] && [ $again != 'y' ] && [ $again != 'N' ] && [ $again != 'n' ];
do
echo "Masukkan yang anda pilih tidak ada di menu";
echo -n "Kembali ke menu? [y/n]: ";
read again;
done
done
